### PR TITLE
Update .gitignore with .coq-native

### PR DESCRIPTION
**Pull request by JasonGross**
For builds with native compiler enabled

### CODE REVIEW

**Comment by tchajed** [comment]
Thanks! I would prefer `.coq-native/` to clarify that it's a directory but I can make that change myself.

**Comment by JasonGross** [comment]
> Thanks! I would prefer `.coq-native/` to clarify that it's a directory but I can make that change myself.

I think this would result in only top-level `.coq-native` folders being ignored, whereas we want to ignore all `.coq-native` folders.  Do you need something like `**/.coq-native/`?

**Comment by JasonGross** [comment]
> I think this would result in only top-level `.coq-native` folders being ignored, whereas we want to ignore all `.coq-native` folders. Do you need something like `**/.coq-native/`?

Just tested this, and I was wrong `.coq-native/` works fine

**Comment by tchajed** [comment]
No, the syntax for that is `/.coq-native`. A trailing slash only matches a directory.

**Pull request merged**
